import Header from './Components/Header'
import { AppContext } from './context/ContextApi'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Youtube Clone',
  description: 'Generated by Avinash Chandraker',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContext>
          <Header/>
          {children}
        </AppContext>
      </body>
    </html>
  )
}
